apiVersion: v1
kind: Service
metadata:
  name: api-opa
  labels:
    app: api-opa
spec:
  type: NodePort
  ports:
  - port: 8001 
    protocol: TCP
    targetPort: 8000
    nodePort: 31000
  selector:
    app: api-opa