apiVersion: v1
kind: PersistentVolume
metadata:
  name: project-mysql-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
     namespace: default
     name: project-mysql-pvc
  hostPath:
    path: /mnt/data/mysql