apiVersion: v1
kind: Service
metadata:
  name: project-mysql
  labels:
    app: project-mysql
spec:
  type: ClusterIP
  clusterIP: 10.43.0.42
  ports:
  - port: 3307 
    targetPort: 3306
    protocol: TCP
  selector:
    app: project-mysql